### ISSUE TITLE
What's differerence between two EFIs?

### ISSUE THREAD

**Issue by izumiiAoba** [Keylem/ThinkPad-E14-Gen3-AMD-Ryzen-5-5500U-Hackintosh#8]
one used to boot recovery, another only used after install
is there some config in plist will affect recovery?
i built my own EFI for my device *thinkpad X13 5600U*
but now come across some stuck
want to know which EFI i could refer to

**Comment by Keylem** [comment]
I built a simple EFI to install from the recovery installer, then I modified it too much that it started doing it. So I kept the initial one just to be able to install the OS and the other one to tweak things etc (because I had a limited time to thinker with it) ... If possible, I would suggest start with the Installer EFI and build on it ; or even better, follow the opencore-install guide's ryzen section and set your settings according to your own configuration. (E series bios is kinda trash and there might be extra options to disabled/enabled by default which would create instability issues on your X series laptop.)

**Comment by izumiiAoba** [comment]
thanks a lot for you kindly reply 😎
i've already booted successfully, after struggling in EFI for about 3 weeks.
